# Generated by Django 3.1.6 on 2021-04-10 22:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('nfc_code', models.CharField(max_length=255, verbose_name='NFC-код')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время и дата операции')),
                ('mass', models.CharField(max_length=255, verbose_name='Масса мусора')),
                ('trash_type', models.CharField(max_length=255, verbose_name='Тип мусора')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='Пользователь')),
            ],
        ),
    ]
